// Auto-generated module index (classic-script build, file:// safe).
// Each module's `reads` lists every resource its page consumes via comm.get.
(function () {
  window.S1 = window.S1 || {};
  window.S1.modulesIndex =
[
  { "name": "dashboard", "title": "Dashboard", "fixture": "dashboard",
    "reads": ["jobs","tasks","reports","auth/me",
              "dashboard/kpis","dashboard/chart","dashboard/performers",
              "dashboard/attention","dashboard/realtime"],
    "writes": [] },
  { "name": "dashboard-v2", "title": "Dashboard (v2)", "fixture": "dashboard-v2",
    "reads": ["jobs","tasks","reports","auth/me",
              "dashboard/kpis","dashboard/chart","dashboard/performers",
              "dashboard/attention","dashboard/realtime"],
    "writes": [] },
  { "name": "scheduling", "title": "Scheduling", "fixture": "scheduling",
    "reads": ["jobs","crews"], "writes": ["jobs"] },
  { "name": "jobDetail", "title": "Job Detail", "fixture": "jobDetail",
    "reads": ["jobs","customers","finance/invoices","documents"], "writes": ["jobs"] },
  { "name": "jobCalendar", "title": "Job Calendar", "fixture": "jobCalendar",
    "reads": ["jobs"], "writes": ["jobs"] },
  { "name": "tasks", "title": "Tasks", "fixture": "tasks",
    "reads": ["tasks"], "writes": ["tasks"] },
  { "name": "tickets", "title": "Tickets", "fixture": "tickets",
    "reads": ["tickets"], "writes": ["tickets"] },
  { "name": "documents", "title": "Documents", "fixture": "documents",
    "reads": ["documents"], "writes": ["documents"] },
  { "name": "fieldCrew", "title": "Field Crew", "fixture": "fieldCrew",
    "reads": ["crews","jobs"], "writes": [] },
  { "name": "finance", "title": "Finance", "fixture": "finance",
    "reads": ["finance/invoices","finance/payments","finance/pnl","finance/receivables","finance/payables"],
    "writes": ["finance/invoices"] },
  { "name": "crewProcesses", "title": "Crew Processes", "fixture": "crewProcesses",
    "reads": ["crews","settings"], "writes": ["settings"] },
  { "name": "preOfficeSubmissions", "title": "Pre-Office Submissions", "fixture": "preOfficeSubmissions",
    "reads": ["preoffice/submissions"], "writes": ["preoffice/submissions"] },
  { "name": "preOfficeTemplates", "title": "Pre-Office Templates", "fixture": "preOfficeTemplates",
    "reads": ["preoffice/templates"], "writes": ["preoffice/templates"] },
  { "name": "qualityControl", "title": "Quality Control", "fixture": "qualityControl",
    "reads": ["quality/incidents"], "writes": ["quality/incidents"] },
  { "name": "reports", "title": "Reports", "fixture": "reports",
    "reads": ["reports"], "writes": [] },
  { "name": "safetyDashboard", "title": "Safety Dashboard", "fixture": "safetyDashboard",
    "reads": ["safety/incidents"], "writes": ["safety/incidents"] },
  { "name": "salesDashboard", "title": "Sales Dashboard", "fixture": "salesDashboard",
    "reads": ["customers","jobs","sales/pipeline","sales/deals"], "writes": [] },
  { "name": "settings", "title": "Settings", "fixture": "settings",
    "reads": ["settings","auth/me","settings/roles","settings/timezones","settings/languages",
              "settings/theme","settings/notifications","settings/nav"],
    "writes": ["settings"] },
  { "name": "storage", "title": "Storage", "fixture": "storage",
    "reads": ["documents"], "writes": ["documents"] },
  { "name": "videosLibrary", "title": "Videos Library", "fixture": "videosLibrary",
    "reads": ["videos"], "writes": [] }
];
})();
